# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "kavin-app-os"
client_id = "ec8e76dae978ed60a8b0bf773c1ccbf0"
application_url = "https://uw-hyundai-jewish-diamond.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://uw-hyundai-jewish-diamond.trycloudflare.com/auth/callback",
  "https://uw-hyundai-jewish-diamond.trycloudflare.com/auth/shopify/callback",
  "https://uw-hyundai-jewish-diamond.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "om-ext.myshopify.com"
